#!/usr/bin/bash

echo "Deleting old clash-verge-rev files..."
rm -rf clash-verge-rev
echo "Privious clash-verge-rev files have been deleted."

echo "Fetching new clash-verge-rev source code..."
git clone https://github.com/clash-verge-rev/clash-verge-rev.git
echo "Download finished."

echo "Change directory to clash-verge-rev"
cd clash-verge-rev
echo "Switching branch to "main"..."
git switch main
echo "Switch branch successfully."

echo "Modifying source code..."
sed -i s/mihomo-linux-loong64/mihomo-linux-loong64-abi2/g scripts/prebuild.mjs
sed -i s/'"active": true,'/'"active": false,'/g src-tauri/tauri.conf.json
sed -i 's#"@vitejs/plugin-react-swc": "^4.2.1",#"@vitejs/plugin-react": "^5.1.0",#g' package.json
sed -i 's#import react from "@vitejs/plugin-react-swc";#import react from "@vitejs/plugin-react";#g' vite.config.mts
echo "Source code was modified."

echo "Installing npm modules..."
pnpm install
echo "Npm modules have been installed."
echo "Running Prebuild Script..."
pnpm run prebuild
echo "Prebuild finished."
echo "Replcing service files..."
cp -v ../clash-verge-service/target/release/clash-verge-service src-tauri/resources/clash-verge-service-loongarch64-unknown-linux-gnu
cp -v ../clash-verge-service/target/release/install-service src-tauri/resources/install-service-loongarch64-unknown-linux-gnu
cp -v ../clash-verge-service/target/release/uninstall-service src-tauri/resources/uninstall-service-loongarch64-unknown-linux-gnu
echo "Service files have been replaced."

echo "Building..."
cargo tauri build
