#!/usr/bin/bash
echo 'Removing old clash-verge-service files...'
rm -rf clash-verge-service
echo 'Previous clash-verge-service files have been removed.'

echo 'Fetching new clash-verge-service source code...'
git clone https://github.com/clash-verge-rev/clash-verge-service.git
echo 'Download finished.'

cd clash-verge-service
echo 'Building...'
cargo build --release
